version: "3"
services:
    grafana:
        container_name: grafana
        image: "grafana/grafana:latest"
        depends_on:
            - influxdb
            - telegraf
        ports:
            - "3000:3000"
        volumes:
            - ./provisioning/:/etc/grafana/provisioning/
            - ./dashboard/:/opt/dashboard/
        command:
        restart: always
    influxdb:
        container_name: influxdb
        image: influxdb
        ports:
            - "8086:8086"
        restart: always
    telegraf:
        container_name: telegraf
        image: telegraf
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf
